#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Master deployment script for Weighbridge ERP at client site.

.DESCRIPTION
    Six-phase automated deployment:
      Phase 1: System requirements check
      Phase 2: Application install (files, DB, services)
      Phase 3: Security hardening (DPAPI, ACLs, firewall)
      Phase 4: Cloudflare Tunnel setup
      Phase 5: Cloud backup setup (R2)
      Phase 6: Verification

.PARAMETER ConfigFile
    Path to deploy-config.json (generated by Generate-DeploymentConfig.ps1)

.PARAMETER ReleaseDir
    Path to the release package folder (e.g., weighbridge-full-1.0.0)

.PARAMETER SkipPhase
    Array of phase numbers to skip (e.g., @(4,5) to skip tunnel and backup)

.EXAMPLE
    .\Deploy-Full.ps1 -ConfigFile ".\deploy-config.json" -ReleaseDir ".\weighbridge-full-1.0.0"
#>

param(
    [Parameter(Mandatory)] [string]$ConfigFile,
    [string]$ReleaseDir = "",
    [int[]]$SkipPhase   = @()
)

$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"

$WeighbridgeDir = "C:\weighbridge"
$ScriptDir      = $PSScriptRoot
$LogFile        = Join-Path $WeighbridgeDir "logs\deploy_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

# ── Logging ─────────────────────────────────────────────────────────────────
function Write-Log {
    param($Message)
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] $Message"
    if (Test-Path (Split-Path $LogFile)) { Add-Content -Path $LogFile -Value $line -Encoding UTF8 }
    Write-Host $line
}

function Write-Phase {
    param($Num, $Title)
    $border = "=" * 55
    Write-Host "`n$border" -ForegroundColor Cyan
    Write-Host "  PHASE $Num: $Title" -ForegroundColor Cyan
    Write-Host "$border`n" -ForegroundColor Cyan
    Write-Log "=== PHASE $Num: $Title ==="
}

function Write-OK   { param($msg) Write-Host "  [OK] $msg" -ForegroundColor Green; Write-Log "[OK] $msg" }
function Write-FAIL { param($msg) Write-Host "  [FAIL] $msg" -ForegroundColor Red; Write-Log "[FAIL] $msg" }
function Write-WARN { param($msg) Write-Host "  [WARN] $msg" -ForegroundColor Yellow; Write-Log "[WARN] $msg" }
function Write-INFO { param($msg) Write-Host "  $msg" -ForegroundColor White; Write-Log "$msg" }

# ── Banner ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════╗" -ForegroundColor White
Write-Host "  ║   Weighbridge ERP — Full Deployment Pipeline  ║" -ForegroundColor White
Write-Host "  ║   Version 1.0 — Secure On-Premise + Cloud     ║" -ForegroundColor White
Write-Host "  ╚═══════════════════════════════════════════════╝" -ForegroundColor White
Write-Host ""

# Load config
if (-not (Test-Path $ConfigFile)) { throw "Config file not found: $ConfigFile" }
$config = Get-Content $ConfigFile -Raw | ConvertFrom-Json
Write-INFO "Client: $($config.client_name) ($($config.client_id))"
Write-INFO "Target: $WeighbridgeDir"
Write-INFO "Log:    $LogFile"

# Create base directories
@($WeighbridgeDir, (Join-Path $WeighbridgeDir "logs"), (Join-Path $WeighbridgeDir "backups")) | ForEach-Object {
    if (-not (Test-Path $_)) { New-Item -ItemType Directory -Path $_ -Force | Out-Null }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 1: System Requirements
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 1) {
    Write-Phase 1 "System Requirements Check"

    # OS check
    $os = Get-CimInstance Win32_OperatingSystem
    if ($os.Caption -match "Windows 1[01]|Windows Server 20(19|22|25)") {
        Write-OK "OS: $($os.Caption)"
    } else {
        Write-FAIL "Unsupported OS: $($os.Caption)"
        exit 1
    }

    # Architecture
    if ([Environment]::Is64BitOperatingSystem) {
        Write-OK "Architecture: 64-bit"
    } else {
        Write-FAIL "32-bit OS not supported"
        exit 1
    }

    # RAM
    $ramGB = [math]::Round($os.TotalVisibleMemorySize / 1MB, 1)
    if ($ramGB -ge 7) {
        Write-OK "RAM: $ramGB GB"
    } else {
        Write-WARN "RAM: $ramGB GB (minimum 8 GB recommended)"
    }

    # Disk space
    $disk = Get-PSDrive C
    $freeGB = [math]::Round($disk.Free / 1GB, 1)
    if ($freeGB -ge 5) {
        Write-OK "Free disk: $freeGB GB"
    } else {
        Write-FAIL "Insufficient disk: $freeGB GB (minimum 5 GB required)"
        exit 1
    }

    # Docker
    $dockerRunning = docker ps 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-OK "Docker Desktop: Running"
    } else {
        Write-WARN "Docker not running — PostgreSQL must be installed natively"
    }

    # Internet
    try {
        $null = Invoke-WebRequest -Uri "https://api.telegram.org" -TimeoutSec 5 -UseBasicParsing
        Write-OK "Internet connectivity: OK"
    } catch {
        Write-WARN "No internet — Cloudflare Tunnel and backups will not work until connected"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 2: Application Install
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 2) {
    Write-Phase 2 "Application Install"

    # Check if Install-Client.ps1 exists and delegate to it
    $clientInstaller = Join-Path $ScriptDir "Install-Client.ps1"
    if ((Test-Path $clientInstaller) -and $ReleaseDir) {
        Write-INFO "Running Install-Client.ps1..."
        & $clientInstaller -ReleaseDir $ReleaseDir -LicenseKey (Join-Path (Split-Path $ConfigFile) "license.key")
        if ($LASTEXITCODE -ne 0) {
            Write-FAIL "Install-Client.ps1 failed (exit code $LASTEXITCODE)"
            exit 1
        }
        Write-OK "Application installed"
    } else {
        # Manual steps if installer not available
        Write-INFO "Checking existing installation..."
        $backendExe = Join-Path $WeighbridgeDir "backend\weighbridge_server.exe"
        $backendSrc = Join-Path $WeighbridgeDir "backend\app\main.py"
        if ((Test-Path $backendExe) -or (Test-Path $backendSrc)) {
            Write-OK "Backend already installed"
        } else {
            Write-WARN "Backend not found — install manually or provide -ReleaseDir"
        }

        $frontendDist = Join-Path $WeighbridgeDir "frontend\dist\index.html"
        if (Test-Path $frontendDist) {
            Write-OK "Frontend already installed"
        } else {
            Write-WARN "Frontend dist not found"
        }

        # License
        $licSrc = Join-Path (Split-Path $ConfigFile) "license.key"
        $licDst = Join-Path $WeighbridgeDir "license.key"
        if ((Test-Path $licSrc) -and -not (Test-Path $licDst)) {
            Copy-Item $licSrc $licDst -Force
            Write-OK "License key installed"
        } elseif (Test-Path $licDst) {
            Write-OK "License key already in place"
        }
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 3: Security Hardening
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 3) {
    Write-Phase 3 "Security Hardening"

    $hardenScript = Join-Path $WeighbridgeDir "backend\hardening\secure_setup.ps1"
    if (Test-Path $hardenScript) {
        Write-INFO "Running secure_setup.ps1..."
        & $hardenScript
        Write-OK "OS hardening complete"
    } else {
        Write-WARN "secure_setup.ps1 not found — applying basic security..."

        # Firewall rules
        try {
            New-NetFirewallRule -DisplayName "Weighbridge Backend" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 9001 -ErrorAction SilentlyContinue | Out-Null
            New-NetFirewallRule -DisplayName "Weighbridge Frontend" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 9000 -ErrorAction SilentlyContinue | Out-Null
            New-NetFirewallRule -DisplayName "Block External PostgreSQL" -Direction Inbound -Action Block -Protocol TCP -LocalPort 5432 -RemoteAddress "Any" -ErrorAction SilentlyContinue | Out-Null
            Write-OK "Firewall rules configured"
        } catch {
            Write-WARN "Could not configure firewall: $_"
        }
    }

    # DPAPI encryption
    $dpapiScript = Join-Path $WeighbridgeDir "backend\setup_dpapi.py"
    $dpapiFile   = Join-Path $WeighbridgeDir "backend\secrets.dpapi"
    if ((Test-Path $dpapiScript) -and -not (Test-Path $dpapiFile)) {
        Write-INFO "Encrypting secrets with DPAPI..."
        Push-Location (Join-Path $WeighbridgeDir "backend")
        python setup_dpapi.py --no-prompt 2>&1 | ForEach-Object { Write-Host "    $_" }
        Pop-Location
        if (Test-Path $dpapiFile) {
            Write-OK "DPAPI encryption complete"
            # Remove .env.bak from machine (should be backed up to USB)
            $envBak = Join-Path $WeighbridgeDir "backend\.env.bak"
            if (Test-Path $envBak) {
                Write-WARN ".env.bak exists — copy to USB drive, then delete from machine!"
            }
        } else {
            Write-WARN "DPAPI encryption may have failed"
        }
    } elseif (Test-Path $dpapiFile) {
        Write-OK "DPAPI already configured"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 4: Cloudflare Tunnel
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 4) {
    Write-Phase 4 "Cloudflare Tunnel Setup"

    if ($config.tunnel_token) {
        $tunnelScript = Join-Path $ScriptDir "Setup-CloudflareTunnel.ps1"
        if (Test-Path $tunnelScript) {
            & $tunnelScript -TunnelToken $config.tunnel_token
            Write-OK "Cloudflare Tunnel configured"
        } else {
            Write-FAIL "Setup-CloudflareTunnel.ps1 not found at $tunnelScript"
        }
    } else {
        Write-WARN "No tunnel_token in config — skipping Cloudflare Tunnel"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 5: Cloud Backup
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 5) {
    Write-Phase 5 "Cloud Backup Setup (Cloudflare R2)"

    if ($config.r2_access_key -and $config.r2_secret_key -and $config.r2_account_id) {
        $backupScript = Join-Path $ScriptDir "Setup-CloudBackup.ps1"
        if (Test-Path $backupScript) {
            $backupParams = @{
                R2AccessKey = $config.r2_access_key
                R2SecretKey = $config.r2_secret_key
                R2AccountId = $config.r2_account_id
                ClientId    = $config.client_id
            }
            if ($config.r2_bucket)          { $backupParams.R2Bucket         = $config.r2_bucket }
            if ($config.telegram_bot_token) { $backupParams.TelegramBotToken = $config.telegram_bot_token }
            if ($config.telegram_chat_id)   { $backupParams.TelegramChatId   = $config.telegram_chat_id }

            & $backupScript @backupParams
            Write-OK "Cloud backup configured"
        } else {
            Write-FAIL "Setup-CloudBackup.ps1 not found at $backupScript"
        }
    } else {
        Write-WARN "R2 credentials not in config — skipping cloud backup"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# PHASE 6: Verification
# ═══════════════════════════════════════════════════════════════════════════
if ($SkipPhase -notcontains 6) {
    Write-Phase 6 "Deployment Verification"

    $verifyScript = Join-Path $ScriptDir "Verify-Deployment.ps1"
    if (Test-Path $verifyScript) {
        $publicUrl = if ($config.public_url) { $config.public_url } else { "" }
        & $verifyScript -PublicUrl $publicUrl -OutputFile (Join-Path $WeighbridgeDir "deployment-report.json")
    } else {
        Write-WARN "Verify-Deployment.ps1 not found"
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# DONE
# ═══════════════════════════════════════════════════════════════════════════
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "  ║     DEPLOYMENT COMPLETE!                      ║" -ForegroundColor Green
Write-Host "  ╚═══════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Client:      $($config.client_name)" -ForegroundColor White
Write-Host "  Local URL:   http://localhost:9000" -ForegroundColor Cyan
if ($config.public_url) {
    Write-Host "  Public URL:  $($config.public_url)" -ForegroundColor Cyan
}
Write-Host "  Log file:    $LogFile" -ForegroundColor Gray
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Login: admin / admin123 → change password immediately" -ForegroundColor White
Write-Host "  2. Settings → Company → enter GSTIN, PAN, bank details" -ForegroundColor White
Write-Host "  3. Settings → Weight Scale → configure COM port" -ForegroundColor White
Write-Host "  4. Settings → Cameras → configure snapshot URLs" -ForegroundColor White
Write-Host "  5. Create financial year" -ForegroundColor White
Write-Host "  6. Create operator accounts" -ForegroundColor White
Write-Host "  7. Test: token → weigh → invoice → PDF → print" -ForegroundColor White
Write-Host ""
